name: Docker image build test

on:
  push:
    branches: [main] # triggered when push to main

jobs:
  build-docker-images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Build the Docker image
        run: |
          docker --version # print the version for logging
          docker compose -f ./docker-compose-build.yaml build --parallel
          docker tag udagram-api-feed braimo/udagram-api-feed:v3
          docker tag udagram-api-user braimo/udagram-api-user:v3
          docker tag udagram-frontend braimo/udagram-frontend:v3
          docker tag reverseproxy braimo/reverseproxy:v3

      - name: Push to Docker hub
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD # log into docker hub account
          docker push braimo/udagram-api-feed:v3
          docker push braimo/udagram-api-user:v3
          docker push braimo/udagram-frontend:v3
          docker push braimo/reverseproxy:v3
