name: Docker image build and push

on:
  push:
    branches: [main] # triggered when push to main

jobs:
  build-push-docker-images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Build the Docker image
        run: |
          docker --version # print the version for logging
          docker compose -f ./docker-compose-build.yaml build --parallel
          docker tag udagram-api-feed braimo/udagram-api-feed:v4
          docker tag udagram-api-user braimo/udagram-api-user:v4
          docker tag udagram-frontend braimo/udagram-frontend:v4
          docker tag reverseproxy braimo/reverseproxy:v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker hub
        run: |
          docker push braimo/udagram-api-feed:v4
          docker push braimo/udagram-api-user:v4
          docker push braimo/udagram-frontend:v4
          docker push braimo/reverseproxy:v4
