name: Docker image build test

on:
  push:
    branches: [dev]


jobs:
  build-docker-images:

    runs-on: ubuntu-latest


    steps:
    - name: Build the Docker image
      run: docker --version # print the version for logging
      run: docker compose -f ./docker-compose-build.yaml build --parallel
      run: docker tag udagram-api-feed sudkul/udagram-api-feed:v1
      run: docker tag udagram-api-user sudkul/udagram-api-user:v1
      run: docker tag udagram-frontend sudkul/udagram-frontend:v1
      run: docker tag reverseproxy sudkul/reverseproxy:v1
