name: Docker image build test

on:
  push:
    branches: [dev]


jobs:
  build-docker-images:

    runs-on: ubuntu-latest


    steps:
    - users: actions/checkout@v3
      with:
        ref: dev
    - name: Build the Docker image
      run: |
        docker --version # print the version for logging
        docker compose -f ./docker-compose-build.yaml build --parallel
        docker tag udagram-api-feed sudkul/udagram-api-feed:v1
        docker tag udagram-api-user sudkul/udagram-api-user:v1
        docker tag udagram-frontend sudkul/udagram-frontend:v1
        docker tag reverseproxy sudkul/reverseproxy:v1
